# WaQtor Funding & Support
# Support the development of WaQtor

# GitHub Sponsors
github: [tariqsaidofficial]

# Buy Me a Coffee
custom: 
  - "https://buymeacoffee.com/tariqsaidofficial"
  - "https://github.com/sponsors/tariqsaidofficial"
  - "https://dxbmark.com/support"
  - "https://linkedin.com/in/tariqsaidofficial"
