services:
  # Redis for Queue Management
  redis:
    image: redis:7-alpine
    container_name: waqtor-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - waqtor-redis:/data
    networks:
      - waqtor-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    command: redis-server --appendonly yes

  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: waqtor-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - API_KEY=${API_KEY:-your-api-key-here}
      - READONLY_FORK=false
      - CORS_ORIGIN=http://localhost:3000,http://dashboard:3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      # Source code (for hot reload)
      - ./runtime:/app/runtime
      - ./src:/app/src
      - ./index.js:/app/index.js
      - ./shell.js:/app/shell.js
      # Persistent data (use Docker volumes to avoid host conflicts)
      - waqtor-sessions:/app/.wwebjs_auth
      - waqtor-cache:/app/.wwebjs_cache
      - waqtor-logs:/app/runtime/logs
      - waqtor-uploads:/app/uploads
      # Exclude session folder from runtime mount to avoid conflicts
      - waqtor-runtime-session:/app/runtime/server/session
      # Node modules (avoid overwriting)
      - /app/node_modules
    networks:
      - waqtor-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    command: npm run dev

  # Frontend Dashboard Service
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
    container_name: waqtor-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # URLs for browser connection (Client-side)
      - NEXT_PUBLIC_BROWSER_API_URL=http://localhost:8080
      - NEXT_PUBLIC_BROWSER_WS_URL=ws://localhost:8080
      # URLs for Server connection (SSR)
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8080/api
      - NEXT_PUBLIC_WS_URL=ws://backend:8080
      - NEXT_PUBLIC_API_KEY=${API_KEY:-your-api-key-here}
      # Hot reload settings
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Source code (for hot reload)
      - ./dashboard:/app
      # Node modules (avoid overwriting)
      - /app/node_modules
      - /app/.next
    networks:
      - waqtor-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    command: npm run dev

  # Nginx Reverse Proxy (Optional - for production-like setup)
  nginx:
    image: nginx:alpine
    container_name: waqtor-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - waqtor-network
    depends_on:
      - backend
      - dashboard
    profiles:
      - production

volumes:
  waqtor-redis:
    driver: local
  waqtor-sessions:
    driver: local
  waqtor-cache:
    driver: local
  waqtor-logs:
    driver: local
  waqtor-uploads:
    driver: local
  waqtor-runtime-session:
    driver: local

networks:
  waqtor-network:
    driver: bridge
