blank_issues_enabled: false
contact_links:
  - name: WaQtor Support
    url: https://github.com/tariqsaidofficial/WaQtor/discussions
    about: Please ask questions and get support here.
  - name: Email Support
    url: mailto:support@dxbmark.com
    about: Contact us directly for urgent issues.
