name: Publish to npm

on:
  # Only trigger manually to avoid conflicts with manual npm publish
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty to use package.json version)'
        required: false
        type: string

# Required for OIDC / Trusted Publisher
permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: npm-publish
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
      continue-on-error: true
    
    - name: Get version
      id: version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "📦 Publishing WaQtor v$VERSION"
    
    - name: Check if version already published
      id: check_version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        if npm view waqtor@$VERSION version 2>/dev/null; then
          echo "Version $VERSION is already published on npm"
          echo "published=true" >> $GITHUB_OUTPUT
          exit 1
        else
          echo "Version $VERSION is not published yet"
          echo "published=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Publish to npm with provenance
      if: steps.check_version.outputs.published == 'false'
      run: npm publish --provenance --access public
      env:
        # Fallback to NPM_TOKEN if OIDC is not yet configured
        # After first publish and Trusted Publisher setup, OIDC will be used automatically
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
